name: Clojure CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_HOST: localhost
      DATABASE_DB: ci_test
      DATABASE_USER: github_ci
      DATABASE_PASSWORD: password

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: github_ci
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ci_test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Rollback and Migrate DB
      run: lein rollback && lein migrate
      env:
        DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
    - name: Run tests
      run: lein test
      env:
        DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
